### ISSUE TITLE
Default Selected not working?

### ISSUE THREAD

**Issue by phucvo0709** [hjyue1/react-do-tree-select#1]
my code:

    const {treeData, category_data} = this.props;
    const checkbox = {
      enable: true,
      parentChain: true, // child Affects parent nodes;
      childrenChain: true, // parent Affects child nodes;
      halfChain: true, // The selection of child nodes affects the semi-selection of parent nodes.
      initCheckedList: category_data // Initialize check multiple lists
    };

    const renderSelect =
      <TreeSelect
        treeData={treeData}
        onChecked={this.onChecked}
        checkbox={checkbox}
      />

**Comment by hjyue1** [comment]
Based on your code, I made an online example：https://codesandbox.io/s/oxr82mm76q, Whether to solve your problem @phucvo0709

**Comment by phucvo0709** [comment]
> Based on your code, I made an online example：[https://codesandbox.io/s/oxr82mm76q，Whether](https://codesandbox.io/s/oxr82mm76q%EF%BC%8CWhether) to solve your problem @phucvo0709

value int not working, you have fix?

**Comment by hjyue1** [comment]
@phucvo0709   Future fixes will be considered. It is recommended that you change the type of the value to a string.

**Comment by phucvo0709** [comment]
> @phucvo0709 Future fixes will be considered. It is recommended that you change the type of the value to a string.

Now I have found the error and fixed it, but I hope you can update it better

**Comment by hjyue1** [comment]
@phucvo0709 ok，I will close this issue
