### ISSUE TITLE
Support Internet Explorer 11

### ISSUE THREAD

**Issue by MarkusLanger** [hjyue1/react-do-tree-select#5]
When I check an option I get an error with Internet Explorer 11.
![InternetExplorer11](https://user-images.githubusercontent.com/12131918/71884923-89062680-3139-11ea-873b-cc02e93cbc1b.gif)

**Comment by hjyue1** [comment]
@MarkusLanger  Hello, this problem is only the online demo is not compatible with IE11, I have fixed it, you can directly use the NPM package
